apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: wild-and-waggy-com-tls
spec:
  secretName: wild-and-waggy-com
  issuerRef: 
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: wildandwaggy.com
  dnsNames: 
    - wildandwaggy.com
    - www.wildandwaggy.com
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - wildandwaggy.com
          - www.wildandwaggy.com